---
title: "Sample Size Calculations"
author: "ks"
date: "6/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if(!require("pwr")){BiocManager::install("pwr")}
library(pwr)
```


```{r figure}
##
## Jung 2005.  sample size calculation
##

samplesize=function(delta,fdr=0.05,power=0.8,pi0=.9){
# assume equal sample sizes
# final n is sample size in each group

	alpha=power*(1-pi0)*fdr/(pi0*(1-fdr))
	beta = 1-power
	zalpha = qnorm(1-alpha/2)
	zbeta = qnorm(1-beta)
	n = 2*(zalpha+zbeta)^2/delta^2
	n
}
samplesize(1,fdr=0.01,power=0.6,pi0=.99)

delta = seq(1,2,.01)
nr=length(delta)
sampsiz=rep(NA,nr)
for (i in 1:nr) sampsiz[i]=samplesize(delta[i],pi0=.95)
par(mar=c(6,6,4,4))
plot(delta,sampsiz,type="l",ylab="Sample Size in Each Group",
	ylim=c(0,32),lwd=2,cex.axis=2,lwd.axis=2,cex.lab=2)
for (i in 1:nr) sampsiz[i]=samplesize(delta[i],pi0=.75)
lines(delta,sampsiz,lty=2,lwd=2)
for (i in 1:nr) sampsiz[i]=samplesize(delta[i],pi0=.5)
lines(delta,sampsiz,lty=3,lwd=2)
legend(1.4,30,c("pi0=0.95","pi0=0.75","pi0=0.5"),lty=c(1:3),cex=1.3,lwd=2)
box(lwd=2)
```


```{r ttest}

alpha.star <- function(f=0.05,pio=0.99,G=4000,power=0.6){
  Go <- floor(G*pio)
  r1 <- floor((G-Go)*power)
  eff.sign.level <- r1*f/Go/(1-f)
  eff.sign.level
}
alpha.star(f=.01)

pwr.t.test(d = 1, sig.level = 0.00006122, power = 0.6, type = c("two.sample"), alternative = c("two.sided"))

```


```{r sessioninfo}
sessionInfo()
```
