---
title: "Double dipping"
author: "ks"
date: "`r Sys.Date()`"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require(ggplot2)) {install.packages("ggplot2")}
if (!require(splus2R)) {install.packages("splus2R")}
library(matrixStats)
```



Let's simulate two independent variables (X1, X2) from a random normal distribution, apply k-means with 2 groups, and test differential expression between the 2 clusters.
```{r}
set.seed(160)
xdat <- rmvnorm(100, mean=c(0,0))
colnames(xdat) <- c("X1","X2")
gp <- factor(rep(1:2,each=50))
df <- cbind.data.frame(gp,xdat)
ggplot(df, aes(x = X1, y = X2, color = gp)) +
   geom_point(size=2) +
  labs(color="Set")
```


```{r}
t.test(X1 ~ gp,  data=df)
t.test(X2 ~ gp,  data=df)
```


```{r}
km <- stats::kmeans(xdat[,-1],centers=2,nstart=100)

ggplot(df, aes(x = X1, y = X2, color = factor(km$cluster))) +
   geom_point(size=2) +
  labs(color="Km cluster")
```

```{r}
t.test(X1 ~ factor(km$cluster),  data=df)
t.test(X2 ~ factor(km$cluster),  data=df)
```











